// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package go_micro_srv_consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//货运承运的一批货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

//单个集装箱描述
type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

//托运结果
type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

// 查看货物信息的请求
// 客户端想要从服务端请求数据，必须有请求格式，哪怕为空
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.consignment.GetRequest")
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_3804bf87090b51a9) }

var fileDescriptor_3804bf87090b51a9 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0xff, 0x33, 0xa9, 0xa8, 0xea, 0x05, 0x58, 0xb0, 0x20, 0x0a, 0x20, 0x75, 0x95,
	0x45, 0x39, 0x42, 0x16, 0x55, 0xb6, 0xee, 0x1a, 0x41, 0x49, 0x46, 0xe9, 0x48, 0xc4, 0x0e, 0xb6,
	0x5b, 0xae, 0x06, 0xd7, 0xe0, 0x44, 0xa8, 0x49, 0x43, 0x8d, 0x50, 0x51, 0x77, 0x7e, 0xf3, 0xfc,
	0x3c, 0x9f, 0x47, 0x03, 0xd3, 0x4c, 0x49, 0x43, 0x85, 0x2c, 0x51, 0xda, 0xb8, 0xd2, 0xca, 0x2a,
	0xc6, 0x0b, 0x15, 0x97, 0x94, 0x69, 0x15, 0x1b, 0xbd, 0x8d, 0x1d, 0x3f, 0xfa, 0xf4, 0x20, 0x48,
	0x0e, 0x9a, 0x9d, 0x43, 0x87, 0x72, 0xee, 0x85, 0xde, 0xcc, 0x17, 0x1d, 0xca, 0x59, 0x08, 0x41,
	0x8e, 0x26, 0xd3, 0x54, 0x59, 0x52, 0x92, 0x77, 0x6a, 0xc3, 0x2d, 0xb1, 0x0b, 0x18, 0xbc, 0x23,
	0x15, 0x6b, 0xcb, 0xbb, 0xa1, 0x37, 0xeb, 0x8b, 0xbd, 0x62, 0xd7, 0xe0, 0x6f, 0xd1, 0x18, 0x7c,
	0x7d, 0xa2, 0x9c, 0xf7, 0xeb, 0xdc, 0xa8, 0x29, 0xa4, 0x39, 0x4b, 0x00, 0x32, 0x25, 0xed, 0x8a,
	0x24, 0x6a, 0xc3, 0x7b, 0x61, 0x77, 0x16, 0xcc, 0x6f, 0xe3, 0x63, 0x94, 0x71, 0xd2, 0xde, 0x15,
	0x4e, 0x2c, 0x2a, 0xc1, 0xff, 0x31, 0xfe, 0x80, 0xdf, 0x40, 0x90, 0x6d, 0x8c, 0x55, 0x25, 0xea,
	0x1d, 0x40, 0x03, 0x0e, 0x6d, 0x29, 0xcd, 0x77, 0xdc, 0x4a, 0x53, 0x41, 0xb2, 0xe6, 0xf6, 0xc5,
	0x5e, 0xb1, 0x4b, 0x18, 0x6e, 0x4c, 0x13, 0xea, 0x35, 0xc6, 0x4e, 0xa6, 0x79, 0xf4, 0xe1, 0xc1,
	0x48, 0xa0, 0xa9, 0x94, 0x34, 0xc8, 0x38, 0x0c, 0x33, 0x8d, 0x2b, 0x8b, 0x4d, 0xcf, 0x91, 0x68,
	0x25, 0x5b, 0x40, 0xe0, 0xa0, 0xd7, 0x8d, 0x83, 0xf9, 0xfd, 0xbf, 0x7f, 0x6b, 0xcf, 0xc2, 0x4d,
	0xb2, 0x14, 0xc6, 0x8e, 0x34, 0xbc, 0x5b, 0x4f, 0xe9, 0xc4, 0x97, 0x7e, 0x45, 0xa3, 0x31, 0xc0,
	0x02, 0xad, 0xc0, 0xb7, 0x0d, 0x1a, 0x3b, 0xff, 0xf2, 0x60, 0xb2, 0x5c, 0x53, 0x55, 0x91, 0x2c,
	0x96, 0xa8, 0xb7, 0x94, 0x21, 0x7b, 0x86, 0x69, 0x52, 0x7f, 0xc0, 0x5d, 0x86, 0xd3, 0x7a, 0x5d,
	0x45, 0xc7, 0xaf, 0xb5, 0xf3, 0x8a, 0xce, 0xd8, 0x23, 0x4c, 0x16, 0x68, 0x9d, 0x9c, 0x61, 0x77,
	0xc7, 0x83, 0x07, 0xdc, 0xd3, 0x9e, 0x7f, 0x19, 0xd4, 0x9b, 0xfe, 0xf0, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x34, 0xf8, 0xee, 0x64, 0xfe, 0x02, 0x00, 0x00,
}
