// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vessel.proto

package go_micro_srv_vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwerId               string   `protobuf:"bytes,6,opt,name=ower_id,json=owerId,proto3" json:"ower_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c0e45ee319d513, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwerId() string {
	if m != nil {
		return m.OwerId
	}
	return ""
}

//等待运送的货物
type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c0e45ee319d513, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

//返回结果，如果有合适的货轮则返回货轮信息
type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c0e45ee319d513, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.vessel.Response")
}

func init() { proto.RegisterFile("vessel.proto", fileDescriptor_e0c0e45ee319d513) }

var fileDescriptor_e0c0e45ee319d513 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x7c, 0x4e, 0xdb, 0x34, 0xd9, 0x47, 0x38, 0x98, 0x03, 0x56, 0xa1, 0x52, 0x94, 0x53, 0x4e,
	0x3e, 0xb4, 0xe2, 0x03, 0xb8, 0x20, 0xc1, 0x31, 0x45, 0x70, 0xac, 0x5c, 0x67, 0x29, 0x2b, 0x25,
	0x71, 0x14, 0x47, 0x69, 0xf9, 0x19, 0xbe, 0x15, 0xe1, 0xd0, 0xa2, 0xa2, 0x08, 0x6e, 0xeb, 0xd9,
	0xd9, 0xd1, 0xcc, 0x18, 0xce, 0x3a, 0xb4, 0x16, 0x0b, 0x59, 0x37, 0xa6, 0x35, 0xfc, 0x62, 0x6b,
	0x64, 0x49, 0xba, 0x31, 0xd2, 0x36, 0x9d, 0xec, 0x57, 0xc9, 0x3b, 0x03, 0xff, 0xc9, 0x8d, 0xfc,
	0x1c, 0x3c, 0xca, 0x05, 0x8b, 0x59, 0x1a, 0x66, 0x1e, 0xe5, 0x7c, 0x06, 0x81, 0x56, 0xb5, 0xd2,
	0xd4, 0xbe, 0x09, 0x2f, 0x66, 0xe9, 0x24, 0x3b, 0xbe, 0xf9, 0x1c, 0xa0, 0x54, 0xfb, 0xf5, 0x0e,
	0x69, 0xfb, 0xda, 0x8a, 0x91, 0xdb, 0x86, 0xa5, 0xda, 0x3f, 0x3b, 0x80, 0x73, 0x18, 0x57, 0xaa,
	0x44, 0x31, 0x76, 0x62, 0x6e, 0xe6, 0xd7, 0x10, 0xaa, 0x4e, 0x51, 0xa1, 0x36, 0x05, 0x8a, 0x49,
	0xcc, 0xd2, 0x20, 0xfb, 0x06, 0xf8, 0x25, 0x4c, 0xcd, 0x0e, 0x9b, 0x35, 0xe5, 0xc2, 0x77, 0x47,
	0xfe, 0xe7, 0xf3, 0x3e, 0x4f, 0x1e, 0x20, 0x5a, 0xd5, 0xa8, 0xe9, 0x85, 0xb4, 0x6a, 0xc9, 0x54,
	0x27, 0xb6, 0xd8, 0xaf, 0xb6, 0xbc, 0x1f, 0xb6, 0x92, 0x0e, 0x82, 0x0c, 0x6d, 0x6d, 0x2a, 0x8b,
	0x7c, 0x09, 0x7e, 0x5f, 0x81, 0x13, 0xf9, 0xbf, 0xb8, 0x92, 0x03, 0xf5, 0xc8, 0xbe, 0x9a, 0xec,
	0x8b, 0xca, 0x6f, 0x60, 0xda, 0x4f, 0x56, 0x78, 0xf1, 0xe8, 0xaf, 0xab, 0x03, 0x77, 0x81, 0x10,
	0xf5, 0xd0, 0x0a, 0x9b, 0x8e, 0x34, 0xf2, 0x47, 0x88, 0xee, 0xa8, 0xca, 0x6f, 0x8f, 0xf1, 0x93,
	0x41, 0x9d, 0x93, 0xe0, 0xb3, 0xf9, 0x20, 0xe7, 0x10, 0x28, 0xf9, 0xb7, 0xf1, 0xdd, 0x3f, 0x2f,
	0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x90, 0x08, 0xda, 0x69, 0xf7, 0x01, 0x00, 0x00,
}
